import { Toaster } from '@/components/ui/Toaster'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={cn('light bg-neutrals-light text-neutrals-black antialiased', poppins.className)}
    >
      <body className="min-h-screen bg-slate-50 pt-12 antialiased">
        {children}

        <Toaster />
      </body>
    </html>
  )
}
