import Navbar from '@/components/Navbar'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={cn('bg-neutrals-light text-neutrals-black antialiased light', poppins.className)}
    >
      <body className="min-h-screen pt-12 bg-slate-50 antialiased">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
