name: Code Quality Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: Check types, format, and lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install packages
        run: npm ci
      - name: Check types
        run: npm run types
      - name: Run Prettier
        run: npm run prettier:fix
      - name: Run ESLint
        run: npm run eslint:fix
